service: lambdaserverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

plugins:
  - serverless-python-requirements

packages:
  individually: true 

functions:
  saveData:
    handler: handler.lambda_handler
    timeout: 5 #seconds
    memorySize: 128 #mb     