service: saveData

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

plugins:
  - serverless-python-requirements

functions:
  saveData:
    handler: handler.lambda_handler   
